### ISSUE TITLE
How to run/build

### ISSUE THREAD

**Issue by adiramardiani** [MuttakinHasib/Al-Quran#3]
First of all, thank your for this application, I search Quran Application and find your amazing work, thank you so much

I don't have basic in react or electron, but I'm trying to understand it

In the installation instructions you only make it up to the installation dependency stage, but don't write instructions to build into an application.

The requirements that I have just installed are :
- nodejs : 14.16.0
- npm : 6.14.11

I don't really understand whether there are special requirements related to prisma or electrons in this application. I haven't installed Postgresql, but now I have mysql, I change the configuration like this with a root user and a blank password, can I use other database like mysql or I have only to use the Postgree database?

.env
```
DATABASE_URL="mysql://root:''@127.0.0.1:3306/database_name"
```

I try to build use this command :
```
npm run build
```

And my console show error like this
```
λ npm run build

> Al-Quran@0.1.7 build C:\path
> nextron build

[nextron] Clearing previous builds
[nextron] Building renderer process
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[=== ] info  - Generating static pages (0/4)
Error occurred prerendering page "/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: chaptersList is not defined
...
...
[=== ] info  - Generating static pages (3/4){}
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /[id]
```

Can you help me whats my missing step or miss config ?

**Comment by MuttakinHasib** [comment]
https://www.prisma.io/docs/concepts/database-connectors/mysql

please read this docs

**Comment by ace-featherlight** [comment]
Hi @MuttakinHasib  thanks for your answer, my mysql database issue maybe is done, but when I 
```
npm run build
```

Application still can't generate static pages like error message above, still any missing ?

**Comment by MuttakinHasib** [comment]
maybe you have problem with getStaticPath or getStaticProps function

**Comment by adiramardiani** [comment]
Sorry for late feedback @MuttakinHasib , I'm still facing this issue, can you give some advice where file/config I must check about getStaticPath or getStaticProps function ?

**Comment by adiramardiani** [comment]
Can you update README file about electron build this project ?
On installation section you only write about dependency instalation

**Comment by MuttakinHasib** [comment]
actually, Develop branch is already in development mode . I'm still working on this branch/project. After finishing this project I will update the README.md file about how to build this project
